# Project: StomachLang
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Calorie.o CPU.o Edible.o Foods.o Memory.o StomachLang.o Variable.o
LINKOBJ  = main.o Calorie.o CPU.o Edible.o Foods.o Memory.o StomachLang.o Variable.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = StomachLang.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Calorie.o: Calorie.cpp
	$(CPP) -c Calorie.cpp -o Calorie.o $(CXXFLAGS)

CPU.o: CPU.cpp
	$(CPP) -c CPU.cpp -o CPU.o $(CXXFLAGS)

Edible.o: Edible.cpp
	$(CPP) -c Edible.cpp -o Edible.o $(CXXFLAGS)

Foods.o: Foods.cpp
	$(CPP) -c Foods.cpp -o Foods.o $(CXXFLAGS)

Memory.o: Memory.cpp
	$(CPP) -c Memory.cpp -o Memory.o $(CXXFLAGS)

StomachLang.o: StomachLang.cpp
	$(CPP) -c StomachLang.cpp -o StomachLang.o $(CXXFLAGS)

Variable.o: Variable.cpp
	$(CPP) -c Variable.cpp -o Variable.o $(CXXFLAGS)
